services:
  - docker

notifications:
  email: false

before_script:
  - cd php/docker
  - docker login -u="$DOCKER_LOGIN_USER" -p="$DOCKER_LOGIN_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    export DOCKER_TAG="latest";
    else
    export DOCKER_TAG=$TRAVIS_BRANCH;
    fi

script:
  - docker build -t $DOCKER_LOGIN_USER/$DOCKER_IMAGE:$DOCKER_TAG .
  - docker images $DOCKER_LOGIN_USER/$DOCKER_IMAGE:$DOCKER_TAG

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker push $DOCKER_LOGIN_USER/$DOCKER_IMAGE:$DOCKER_TAG;
    fi
